### ISSUE TITLE
[BUG] Background of loading comment ignores theme

### ISSUE THREAD

**Issue by laurencedawson** [laurencedawson/sync-for-reddit#431]
https://www.reddit.com/r/redditsync/comments/k1binb/question_after_the_recent_beta_update_my_expand/

**Comment by Waaiez** [comment]
This issue is most likely caused by Android's force dark mode feature. I had the same issue but once force dark mode was disabled for Sync it was fixed.

Force dark mode enabled
![Screenshot_2020-11-30-02-47-02-374_com laurencedawson reddit_sync dev](https://user-images.githubusercontent.com/43832467/100558507-7186dd80-32b7-11eb-8102-98fc0396e59e.jpg)

Force dark mode disabled
![Screenshot_2020-11-30-02-47-08-173_com laurencedawson reddit_sync dev](https://user-images.githubusercontent.com/43832467/100558508-72b80a80-32b7-11eb-939b-6093ce58ac18.jpg)

Device: Xiaomi Redmi Note 7
OS: Android 10 MIUI 12
Version: Sync Dev v20 beta 25

**Comment by laurencedawson** [comment]
Ahh that was it. Cheers, fixed.
