### ISSUE TITLE
[BUG] Getting stuck in inbox

### ISSUE THREAD

**Issue by TerpBE** [laurencedawson/sync-for-reddit#923]
**Describe the bug**
When you are in the inbox, you can't navigate anywhere else.

**To Reproduce**
I just had this happen, and I think it also did yesterday. 

I had a notification of a reply to one of my comments.

I clicked on the notification, then on the message to read it.

I clicked the back button (actually a left swipe with how have my phone's set up), and it took me back to my inbox, with the message now dark (read).

I clicked the back button again, and nothing happened - still in my inbox.

I went to Explore - Front Page, and I was still in my inbox. I tried a couple of times and the same result.

Nothing I did seemed to take me out of the inbox, UNTIL I clicked the INBOX button (which didn't appear to do anything) but then it let me go to Explore - Front Page.

**Expected behavior**
Navigating to somewhere else will actually take you there.

**Screenshots**

**Smartphone (please complete the following information):**
 Google Pixel 6

**Additional context**
I like turtles.

**Comment by laurencedawson** [comment]
Do you have bottom nav enabled?

**Comment by laurencedawson** [comment]
Is this repeatable? I can't seem to duplicate it my end. Cheers

**Comment by TerpBE** [comment]
It happened again today. If you reply to my reddit thread, it'll give me a notification so I can try again.

**Comment by AlexVasiluta** [comment]
I have been able to reproduce this bug!

When the app activity is fully closed (i.e., opening the app will take you to the splash screen), when you receive an inbox notification and open it, it will take you straight to the inbox, but the active view state probably doesn't change for the bottom navigation. 

My theory is this: the app thinks it's on the front page because of the sudden switch to the inbox view on open, so you must tap on the inbox button in order to "notify" sync that you are on the inbox page. Only then can you tap on the main page button and actually change to it, since it thinks it's already there!

**Comment by AlDrag** [comment]
I have the same issue. I liked the way it used to function in the previous version of the app. Pressing back would take you back to your frontpage or whatever, after going to the inbox page from a notification.

**Comment by laurencedawson** [comment]
Added a fix for the next release.
